module.exports = {
  anime: {
    key: "anime",
    name: "日系动漫",
    icon: "🎌",
    basePrompt: "anime style, manga art, 2D animation, cel shaded",
    extendedKeywords: "Japanese anime style, vibrant colors, clean lines, cute aesthetic",
    forbidden: "realistic, photorealistic, cinematic, 3D render, western style",
    characterFeatures: "Asian features, Japanese anime style, kawaii design",
    recommendedFor: ["历史人物", "国风故事", "二次元内容", "古风"],
    colorPalette: ["vibrant", "saturated", "clean", "soft"],
    description: "日系二次元风格，适合可爱、清新的内容",
    previewColor: "#FF6B9D",
  },
  guofeng: {
    key: "guofeng",
    name: "古装国风",
    icon: "🏯",
    basePrompt: "Chinese ancient style, traditional painting, ink wash aesthetic",
    extendedKeywords: "Chinese traditional art, watercolor, historical costume, elegant flowing",
    forbidden: "modern, western style, cyberpunk, futuristic, neon",
    characterFeatures: "Asian features, ancient Chinese costume, elegant traditional styling",
    recommendedFor: ["历史人物", "古代故事", "文化传承", "武侠"],
    colorPalette: ["warm", "muted", "traditional", "elegant"],
    description: "中国古装水墨风格，适合历史、文化类内容",
    previewColor: "#FF6B35",
  },
  modern: {
    key: "modern",
    name: "现代写实",
    icon: "📷",
    basePrompt: "professional photography, cinematic, photorealistic, 8K resolution",
    extendedKeywords: "8K resolution, cinematic lighting, high detail, realistic human features",
    forbidden: "anime, manga, 2D animation, cartoon, pixel art",
    characterFeatures: "realistic human features, natural proportions, modern fashion",
    recommendedFor: ["产品介绍", "现代故事", "科技展示", "商业"],
    colorPalette: ["neutral", "balanced", "realistic", "professional"],
    description: "现代写实摄影风格，适合产品、科技、商业类内容",
    previewColor: "#7C3AED",
  },
  cyberpunk: {
    key: "cyberpunk",
    name: "赛博朋克",
    icon: "",
    basePrompt: "cyberpunk, neon lights, futuristic city, sci-fi aesthetic, high tech",
    extendedKeywords: "neon, futuristic, high-tech, dystopian, cybernetic, holographic",
    forbidden: "historical, ancient, traditional, natural, vintage",
    characterFeatures: "futuristic, tech-enhanced, cybernetic implants, neon accents",
    recommendedFor: ["科技内容", "未来概念", "AI主题", "科幻"],
    colorPalette: ["neon", "contrast", "synthetic", "high-tech"],
    description: "未来科技赛博朋克风格，适合科技、科幻类内容",
    previewColor: "#00D9FF",
  },
  watercolor: {
    key: "watercolor",
    name: "水彩画风",
    icon: "🎨",
    basePrompt: "watercolor painting, soft artistic style, hand-drawn aesthetic",
    extendedKeywords: "watercolor, soft pastel colors, artistic brush strokes, dreamy atmosphere",
    forbidden: "digital, photorealistic, harsh lighting, sharp edges",
    characterFeatures: "hand-drawn artistic style, soft features, watercolor aesthetic",
    recommendedFor: ["艺术创作", "文艺内容", "情感故事", "治愈系"],
    colorPalette: ["soft", "pastel", "artistic", "dreamy"],
    description: "柔和水彩画风格，适合艺术、治愈类内容",
    previewColor: "#4ECDC4",
  },
  retro: {
    key: "retro",
    name: "复古像素",
    icon: "👾",
    basePrompt: "pixel art, 8-bit style, retro gaming aesthetic, nostalgic",
    extendedKeywords: "pixel art, 8-bit, 16-bit, retro gaming, nostalgic, chiptune aesthetic",
    forbidden: "photorealistic, 3D render, modern glossy, high resolution",
    characterFeatures: "pixelated features, retro gaming character design, 8-bit aesthetic",
    recommendedFor: ["游戏内容", "怀旧主题", "复古风格", "娱乐"],
    colorPalette: ["retro", "vibrant", "limited palette", "nostalgic"],
    description: "复古像素艺术风格，适合游戏、怀旧类内容",
    previewColor: "#FF9F1C",
  },
  minimal: {
    key: "minimal",
    name: "极简主义",
    icon: "🧹",
    basePrompt: "minimalist design, clean aesthetic, simple composition, modern graphic",
    extendedKeywords: "minimalist, clean, simple, elegant, modern graphic design, whitespace",
    forbidden: "cluttered, ornate, detailed, busy, complex",
    characterFeatures: "simple design, clean lines, minimalist aesthetic",
    recommendedFor: ["商业展示", "品牌宣传", "简约风格", "高端"],
    colorPalette: ["minimal", "clean", "monochrome", "elegant"],
    description: "极简主义设计风格，适合高端、商业类内容",
    previewColor: "#2C3E50",
  },
  cinematic: {
    key: "cinematic",
    name: "电影大片",
    icon: "🎬",
    basePrompt: "cinematic, Hollywood style, dramatic lighting, blockbuster aesthetic",
    extendedKeywords: "cinematic, dramatic lighting, Hollywood production, epic scale, film grain",
    forbidden: "cartoon, anime, flat, low budget, amateur",
    characterFeatures: "cinematic appearance, dramatic lighting, film production quality",
    recommendedFor: ["电影感", "史诗故事", "商业大片", "高端视频"],
    colorPalette: ["dramatic", "cinematic", "high contrast", "epic"],
    description: "好莱坞电影大片风格，适合史诗、商业大片类内容",
    previewColor: "#E74C3C",
  },
};